variables:
  DOCKER_DAEMON_OPTIONS: "--insecure-registry=${CI_REGISTRY}"
  GIT_DEPTH: 0
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay
  ACCEPT_EULA: Y
  MS_BUILD_WARNINGS_AS_MESSAGES: MSB3026
  NUGET_GITLAB_NETLAND_USERNAME: "${CI_READ_NUGET_REGISTRY_USERNAME}"
  NUGET_GITLAB_NETLAND_PASSWORD: "${CI_READ_NUGET_REGISTRY_PASSWORD}"
  NUGET_PACKAGES_DIRECTORY: '.nuget'
